model_name: faster_rcnn
data:
  train_annotation_path: /data/szy4017/data/intruscapes/annotations/instances_train.json
  val_annotation_path: /data/szy4017/data/intruscapes/annotations/instances_val.json
  train_img_root: /data/szy4017/data/intruscapes/images/train
  val_img_root: /data/szy4017/data/intruscapes/images/val
  max_thresh: 768
  use_crowd: False
  batch_size: 4
  num_workers: 2
  debug: False
  remove_blank: Ture

model:
  num_cls: 2
  backbone: resnet50
  pretrained: True
  reduction: False
  fpn_channel: 256
  fpn_bias: True
  anchor_sizes: [32.0, 64.0, 128.0, 256.0, 512.0]
  anchor_scales: [1.0, ]
  anchor_ratios: [0.5, 1.0, 2.0]
  strides: [4.0, 8.0, 16.0, 32.0, 64.0]
  rpn_pre_nms_top_n_train: 2000
  rpn_post_nms_top_n_train: 2000
  rpn_pre_nms_top_n_test: 1000
  rpn_post_nms_top_n_test: 1000
  rpn_fg_iou_thresh: 0.7
  rpn_bg_iou_thresh: 0.3
  rpn_nms_thresh: 0.7
  rpn_batch_size_per_image: 256
  rpn_positive_fraction: 0.5

  box_fg_iou_thresh: 0.5
  box_bg_iou_thresh: 0.5
  box_batch_size_per_image: 512
  box_positive_fraction: 0.25
  box_score_thresh: 0.05
  box_nms_thresh: 0.5
  box_detections_per_img: 100

optim:
  optimizer: Adam
  lr: 0.00005
  milestones: [24,]
  warm_up_epoch: 0
  weight_decay: 0.0001
  epochs: 24
  sync_bn: True
  amp: True
val:
  interval: 1
  weight_path: /data/szy4017/code/faster_rcnn_COCO/weights


gpus: '1,2'